name: Run Go Script on Schedule

on:
  schedule:
    - cron: "*/1 * * * *" # Run every minute for testing
    # - cron: "0 0 */14 * *"
  workflow_dispatch:

jobs:
  run-go-script:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up Go environment
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22.5"

      # Step 3: Install dependencies (optional)
      - name: Install Dependencies
        run: go mod tidy

      # Step 4: Set environment variables (if needed)
      # - name: Set Environment Variables
      # run: echo "MONGO_URI=${{ secrets.MONGO_URI }}" >> $GITHUB_ENV

      # Step 5: Debug current directory (optional)
      - name: List Files
        run: ls -la

      # Step 6: Print the MONOG_URI to debug if it's being set correctly
      - name: Print MONGO_URI
        run: echo "MONGO_URI=$MONGO_URI"

      # Step 6: Run the Go script
      - name: Run Go Script
        run: go run main.go
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }} # Ensure MONGO_URI is passed as environment variable
          MONGO_DB_NAME: ${{ secrets.MONGO_DB_NAME }}
          MONGO_COLLECTION: ${{ secrets.MONGO_COLLECTION }}
