name: Run Scheduled Job

on:
  schedule:
    # Cron syntax: 'minute hour day-of-month month day-of-week'
    # - cron: '0 0 * * 0' # Runs every Sunday at midnight UTC
    # Explanation:
    # 0 0 means the job runs at midnight.
    # */14 in the day-of-month field specifies every 14 days.
    # * * for months and days of the week means it applies to all.
    - cron: "0 0 */14 * *"

jobs:
  example-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3 # Checks out the code

      - name: Run a Script
        run: echo "Hello! This is a scheduled task running on $(date)."
